import pandas as pd

# Define the MRT lines and their stations
mrt_lines = {
    "East West Line": [
        "PASIR RIS MRT STATION", "TAMPINES MRT STATION", "SIMEI MRT STATION", "TANAH MERAH MRT STATION",
        "BEDOK MRT STATION", "KEMBANGAN MRT STATION", "EUNOS MRT STATION", "PAYA LEBAR MRT STATION",
        "ALJUNIED MRT STATION", "KALLANG MRT STATION", "LAVENDER MRT STATION", "BUGIS MRT STATION",
        "CITY HALL MRT STATION", "RAFFLES PLACE MRT STATION", "TANJONG PAGAR MRT STATION", "OUTRAM PARK MRT STATION",
        "TIONG BAHRU MRT STATION", "REDHILL MRT STATION", "QUEENSTOWN MRT STATION", "COMMONWEALTH MRT STATION",
        "BUONA VISTA MRT STATION", "DOVER MRT STATION", "CLEMENTI MRT STATION", "JURONG EAST MRT STATION",
        "CHINESE GARDEN MRT STATION", "LAKESIDE MRT STATION", "BOON LAY MRT STATION", "PIONEER MRT STATION",
        "JOO KOON MRT STATION", "GUL CIRCLE MRT STATION", "TUAS CRESCENT MRT STATION", "TUAS WEST ROAD MRT STATION", "TUAS LINK"
        # EXPO and CHANGI AIPORT
    ],
    "North South Line": [
        "JURONG EAST MRT STATION", "BUKIT BATOK MRT STATION", "BUKIT GOMBAK MRT STAION", "CHOA CHU KANG MRT STATION",
        "YEW TEE MRT STATION", "KRANJI MRT STATION", "MARSILING MRT STATION", "WOODLANDS MRT STATION",
        "ADMIRALTY MRT STATION", "SEMBAWANG MRT STATION", "CANBERRA MRT STATION", "YISHUN MRT STATION",
        "KHATIB MRT STATION", "YIO CHU KANG MRT STATION", "ANG MO KIO MRT STATION", "BISHAN MRT STATION",
        "BRADDELL MRT STATION", "TOA PAYOH MRT STATION", "NOVENA MRT STATION", "ORCHARD MRT STATION",
        "SOMERSET MRT STATION", "DHOBY GHAUT MRT STATION", "CITY HALL MRT STATION", "RAFFLES PLACE MRT STATION",
        "MARINA BAY MRT STATION", "MARINA SOUTH PIER MRT STATION"
    ],
    "Circle Line": [
        "DHOBY GHAUT MRT STATION", "BRAS BASAH MRT STATION", "ESPLANADE MRT STATION", "PROMENADE MRT STATION",
        "NICOLL HIGHWAY MRT STATION", "STADIUM MRT STATION", "MOUNTBATTEN MRT STATION", "DAKOTA MRT STATION",
        "PAYA LEBAR MRT STATION", "MACPHERSON MRT STATION", "TAI SENG MRT STATION", "BARTLEY MRT STATION",
        "SERANGOON MRT STATION", "LORONG CHUAN MRT STATION", "BISHAN MRT STATION", "MARYMOUNT MRT STATION",
        "CALDECOTT MRT STATION", "BOTANIC GARDENS MRT STATION", "FARRER ROAD MRT STATION", "HOLLAND VILLAGE MRT STATION",
        "BUONA VISTA MRT STATION", "ONE-NORTH MRT STATION", "KENT RIDGE MRT STATION", "HAW PAR VILLA MRT STATION",
        "PASIR PANJANG MRT STATION", "LABRADOR PARK MRT STATION", "TELOK BLANGAH MRT STATION", "HARBOURFRONT MRT STATION"
        # BAYFRONT, MARINA BAY
    ],
    "North East Line": [
        "HARBOURFRONT MRT STATION", "OUTRAM PARK MRT STATION", "CHINATOWN MRT STATION", "CLARKE QUAY MRT STATION",
        "DHOBY GHAUT MRT STATION", "LITTLE INDIA MRT STATION", "FARRER PARK MRT STATION", "BOON KENG MRT STATION",
        "POTONG PASIR MRT STATION", "WOODLEIGH MRT STATION", "SERANGOON MRT STATION", "KOVAN MRT STATION",
        "HOUGANG MRT STATION", "BUANGKOK MRT STATION", "SENGKANG MRT STATION", "PUNGGOL MRT STATION"
    ],
    "Downtown Line": [
        "BUKIT PANJANG MRT STATION", "CASHEW MRT STATION", "HILLVIEW MRT STATION", "BEAUTY WORLD MRT STATION",
        "KING ALBERT PARK MRT STATION", "SIXTH AVENUE MRT STATION", "TAN KAH KEE MRT STATION", "BOTANIC GARDENS MRT STATION",
        "STEVENS MRT STATION", "NEWTON MRT STATION", "LITTLE INDIA MRT STATION", "ROCHOR MRT STATION",
        "BUGIS MRT STATION", "PROMENADE MRT STATION", "BAYFRONT MRT STATION", "DOWNTOWN MRT STATION",
        "TELOK AYER MRT STATION", "CHINATOWN MRT STATION", "FORT CANNING MRT STATION", "BENCOOLEN MRT STATION",
        "JALAN BESAR MRT STATION", "BENDEMEER MRT STATION", "GEYLANG BAHRU MRT STATION", "MATTAR MRT STATION",
        "MACPHERSON MRT STATION", "UBI MRT STATION", "KAKI BUKIT MRT STATION", "BEDOK NORTH MRT STATION",
        "BEDOK RESERVOIR MRT STATION", "TAMPINES WEST MRT STATION", "TAMPINES MRT STATION", "TAMPINES EAST MRT STATION",
        "UPPER CHANGI MRT STATION", "EXPO MRT STATION"
    ],
    "Thomson-East Coast Line": [
        "WOODLANDS NORTH MRT STATION", "WOODLANDS MRT STATION", "WOODLANDS SOUTH MRT STATION", "SPRINGLEAF MRT STATION",
        "LENTOR MRT STATION", "MAYFLOWER MRT STATION", "BRIGHT HILL MRT STATION", "UPPER THOMSON MRT STATION",
        "CALDECOTT MRT STATION", "STEVENS MRT STATION", "NAPIER MRT STATION", "ORCHARD BOULEVARD MRT STATION",
        "ORCHARD MRT STATION", "GREAT WORLD MRT STATION", "HAVELOCK MRT STATION", "OUTRAM PARK MRT STATION",
        "MAXWELL MRT STATION", "SHENTON WAY MRT STATION", "MARINA BAY MRT STATION"
    ]
}

# Create an empty list to hold the connections
connections = []

# Iterate through each MRT line and create connections
for line, stations in mrt_lines.items():
    for i in range(len(stations) - 1):
        connections.append({
            "Station": stations[i],
            "Connected Station": stations[i + 1]
        })
        connections.append({
            "Station": stations[i + 1],
            "Connected Station": stations[i]
        })

# Convert the connections list to a DataFrame
connections_df = pd.DataFrame(connections)

# Save the connections to a new CSV file
output_file_path = './MRT_Stations_Edges.csv'
connections_df.to_csv(output_file_path, index=False)

# Display the first few rows of the new DataFrame
connections_df.head()
